### ISSUE TITLE
Вставка в кольцевой буфер реализована неэффективно

### ISSUE THREAD

**Issue by Dedaulus** [Vasiliy-Evdokimov/weather_station#1]
https://github.com/Vasiliy-Evdokimov/weather_station/blob/0cfa34740b43a89536ba2bc72c32901e91d89b6f/sensor.cpp#L41

Вместо перебора массива с почленным ручным копированием, раз уж у нас здесь POD данные, стоит использовать memmove

**Comment by Vasiliy-Evdokimov** [comment]
fixed
