### ISSUE TITLE
Методы должны быть константными

### ISSUE THREAD

**Issue by Dedaulus** [Vasiliy-Evdokimov/weather_station#3]
https://github.com/Vasiliy-Evdokimov/weather_station/blob/0cfa34740b43a89536ba2bc72c32901e91d89b6f/sensor.h#L22

Если метод не меняет состояние класса, он должен быть константным

String getCaption();
String getMeasurement();
uint32_t getColor();
void_function_pointer getPlotFunction();

**Comment by Vasiliy-Evdokimov** [comment]
fixed
